'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import Link from 'next/link'
import { usePlan, usePlanTasks, useDeletePlan } from '@/features/Plans'
import { ConfirmDeleteDialog } from '@/features/Plans'
import { TaskCard } from '@/features/tasks/components/TaskCard'
import { Task } from '@/features/tasks'
import { PAGE_THEME, ThemeKey } from '@/Common/Constants/ThemeConstants'

// ─── Theme ────────────────────────────────────────────────────────────────────

const SOURCE_LABEL: Record<string, { light: string; dark: string; text: string }> = {
  mcp: {
    text: 'Generated by Claude',
    light: 'bg-[#f0eeff] text-[#4a35b0]',
    dark: 'bg-[#1e1a3a] text-[#9a82ff]',
  },
  manual: {
    text: 'Manual',
    light: 'bg-[#f5f5f7] text-[#6b6b80]',
    dark: 'bg-[#24243a] text-[#7070a0]',
  },
}

// ─── Icons ───────────────────────────────────────────────────────────────────

function ArrowLeftIcon() {
  return (
    <svg width="14" height="14" viewBox="0 0 14 14" fill="none" aria-hidden="true">
      <path d="M8.75 3.5L4.25 7l4.5 3.5" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
    </svg>
  )
}

function TrashIcon() {
  return (
    <svg width="13" height="13" viewBox="0 0 13 13" fill="none" aria-hidden="true">
      <path d="M2 3.5h9M4.5 3.5V2.5a1 1 0 011-1h2a1 1 0 011 1v1M5.5 6v3M7.5 6v3M3 3.5l.5 7a1 1 0 001 1h4a1 1 0 001-1l.5-7" stroke="currentColor" strokeWidth="1" strokeLinecap="round"/>
    </svg>
  )
}

// ─── Skeleton ─────────────────────────────────────────────────────────────────

function TaskSkeleton({ theme }: { theme: ThemeKey }) {
  const t = PAGE_THEME[theme]
  return <div className={`h-[58px] rounded-[10px] animate-pulse ${t.skeleton}`} aria-hidden="true" />
}

// ─── Page ─────────────────────────────────────────────────────────────────────

interface PlanDetailPageProps {
  params: { id: string }
}

export default function PlanDetailPage({ params }: PlanDetailPageProps) {
  const theme: ThemeKey = 'dark'
  const t = PAGE_THEME[theme]
  const router = useRouter()

  const { data: plan, isLoading: planLoading, isError: planError } = usePlan(params.id)
  const { data: tasks, isLoading: tasksLoading } = usePlanTasks(params.id)
  const { mutate: deletePlan, isPending: isDeleting } = useDeletePlan()

  const [confirmOpen, setConfirmOpen] = useState(false)

  const handleDelete = () => {
    deletePlan(params.id, {
      onSuccess: () => {
        setConfirmOpen(false)
        router.push('/plans')
      },
    })
  }

  if (planError) {
    return (
      <div className={`min-h-screen ${t.bg}`}>
        <div className="max-w-3xl mx-auto px-8 py-10">
          <Link href="/plans" className={`inline-flex items-center gap-1.5 text-sm mb-6 transition-colors duration-150 ${t.back}`}>
            <ArrowLeftIcon /> Back to plans
          </Link>
          <p className={`text-[14px] ${t.body}`}>
            This plan couldn&apos;t be found — it may have already been deleted.
          </p>
        </div>
      </div>
    )
  }

  const badge = plan ? SOURCE_LABEL[plan.source] : null

  return (
    <div className={`min-h-screen ${t.bg}`}>
      <div className="max-w-3xl mx-auto px-8 py-10">
        <Link href="/plans" className={`inline-flex items-center gap-1.5 text-sm mb-6 transition-colors duration-150 ${t.back}`}>
          <ArrowLeftIcon /> Back to plans
        </Link>

        {/* ── Header ── */}
        {planLoading ? (
          <div className={`h-7 w-2/3 rounded-md animate-pulse mb-3 ${t.skeleton}`} />
        ) : plan ? (
          <header className="mb-8">
            <div className="flex items-start justify-between gap-4 mb-3">
              <h1 className={`text-2xl font-bold ${t.heading}`}>{plan.title}</h1>
              <button
                type="button"
                className={`shrink-0 inline-flex items-center gap-1.5 h-8 px-3 rounded-[7px] border text-[12px] font-medium cursor-pointer transition-[background,color,border-color] duration-150 ${t.deleteBtn}`}
                onClick={() => setConfirmOpen(true)}
                aria-label="Delete plan"
              >
                <TrashIcon />
                Delete plan
              </button>
            </div>

            {plan.goalDescription && (
              <p className={`text-[14px] leading-[1.6] mb-3 ${t.body}`}>{plan.goalDescription}</p>
            )}

            {badge && (
              <span className={`inline-flex items-center text-[11px] font-medium px-2 py-0.5 rounded-[5px] ${badge[theme]}`}>
                {badge.text}
              </span>
            )}
          </header>
        ) : null}

        {/* ── Task list ── */}
        <div className={`pt-2 border-t mb-4 ${t.divider}`}>
          <h2 className={`text-[13px] font-medium mt-5 mb-3 ${t.subheading}`}>
            {tasksLoading ? 'Tasks' : `${tasks?.length ?? 0} task${tasks?.length === 1 ? '' : 's'}`}
          </h2>
        </div>

        {tasksLoading && (
          <div className="flex flex-col gap-1.5">
            {Array.from({ length: 3 }).map((_, i) => <TaskSkeleton key={i} theme={theme} />)}
          </div>
        )}

        {!tasksLoading && tasks && tasks.length === 0 && (
          <p className={`text-[13px] ${t.subheading}`}>No tasks in this plan.</p>
        )}

        {!tasksLoading && tasks && tasks.length > 0 && (
          <div className="flex flex-col gap-1.5" role="list">
            {tasks.map((task : Task) => (
              <div key={task.id} role="listitem">
                <TaskCard task={task} theme={theme} />
              </div>
            ))}
          </div>
        )}
      </div>

      <ConfirmDeleteDialog
        open={confirmOpen}
        planTitle={plan?.title ?? ''}
        taskCount={tasks?.length}
        isDeleting={isDeleting}
        onConfirm={handleDelete}
        onCancel={() => setConfirmOpen(false)}
        theme={theme}
      />
    </div>
  )
}