'use client'

import Link from 'next/link'
import { THEMES } from '@/features/tasks/components/TaskCard'
import type { Plan } from '../types'

// ─── Source badge ───────────────────────────────────────────────────────────

const SOURCE_BADGE: Record<Plan['source'], { label: string; light: string; dark: string }> = {
  mcp: {
    label: 'Generated by Claude',
    light: 'bg-[#f0eeff] text-[#4a35b0]',
    dark: 'bg-[#1e1a3a] text-[#9a82ff]',
  },
  manual: {
    label: 'Manual',
    light: 'bg-[#f5f5f7] text-[#6b6b80]',
    dark: 'bg-[#24243a] text-[#7070a0]',
  },
}

// ─── Icons ───────────────────────────────────────────────────────────────────

function SparkleIcon() {
  return (
    <svg width="11" height="11" viewBox="0 0 11 11" fill="none" aria-hidden="true">
      <path d="M5.5 1l1.2 3.6H10L7 6.8l1.1 3.7L5.5 8.4 2.9 10.5 4 6.8 1 4.6h3.3L5.5 1z" stroke="currentColor" strokeWidth="0.8" strokeLinejoin="round"/>
    </svg>
  )
}

function ChevronIcon() {
  return (
    <svg width="14" height="14" viewBox="0 0 14 14" fill="none" aria-hidden="true">
      <path d="M5.25 3.5l4.5 3.5-4.5 3.5" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
    </svg>
  )
}

// ─── Component ────────────────────────────────────────────────────────────────

interface PlanCardProps {
  plan: Plan
  theme?: 'light' | 'dark'
}

export function PlanCard({ plan, theme = 'light' }: PlanCardProps) {
  const t = THEMES[theme]
  const badge = SOURCE_BADGE[plan.source]
  

  return (
    <Link
      href={`/plans/${plan.id}`}
      className={`group flex items-center gap-3.5 border rounded-[10px] px-4 py-3.5 transition-[border-color,background] duration-150 ${t.card}`}
      aria-label={`Open plan: ${plan.title}`}
    >
      <div className="flex-1 min-w-0">
        <div className={`text-[14px] font-semibold mb-1 truncate ${t.title}`}>
          {plan.title}
        </div>
        {plan.goalDescription && (
          <p className={`text-[12px] leading-[1.5] mb-2 line-clamp-1 ${t.description}`}>
            {plan.goalDescription}
          </p>
        )}
        <div className="flex items-center gap-1.5 flex-wrap">
          <span className={`inline-flex items-center gap-1 text-[11px] font-medium px-2 py-0.5 rounded-[5px] ${badge[theme]}`}>
            {plan.source === 'mcp' && <SparkleIcon />}
            {badge.label}
          </span>
          
        </div>
      </div>

      <span className={`shrink-0 transition-transform duration-150 group-hover:translate-x-0.5 ${t.score}`}>
        <ChevronIcon />
      </span>
    </Link>
  )
}